### ISSUE TITLE
Images on SSD1306 are displaced right and down

### ISSUE THREAD

**Issue by Shirkamdev** [rm-hull/luma.oled#225]
I'm testing a SSD1306 display on a Raspberry Pi 3. This board uses SPI. With every example I execute, the drawings appear padded right and down as the middle of the screen. If the demo is animated, drawings start moving down and right, and the part that cannot be drawn due to being out of screen, appears up in the screen.

Here is an example of what's happening:
![img-20181104-wa0014](https://user-images.githubusercontent.com/13131694/47969633-e2c51980-e07a-11e8-9c02-5abd441bc896.jpg)

I'm launching this example with `python demo.py --interface spi`
I have a running driver, and I've checked all values to see if example defaults are the same, every one of them is correct. I don't know what is happening, as the older driver behaves correctly.

**Comment by rm-hull** [comment]
When you said: _"as the older driver behaves correctly"_, what do you mean by that?

There are two possibilities AFAICS:
* Are you certain it is an SSD1306 rather than a SH1106 ?
* Alternatively, it looks as though the memory is remapped from a different offset ... Could you try running the demo with the `--h-offset H_OFFSET` switch, eg. `python demo.py --interface spi --h-offset -32` ... maybe try a few different values to see if you can get it to align properly

**Comment by Shirkamdev** [comment]
I'm sure is not a SH1106, if I change the display to that, it does weirder things with the image.
Also, if I use the offset, it doesn't change the image position at all, it's still displaced from the corner.
When I said that "old driver" thing, I'm saying that the screen is working right now with a (crappy) old driver. I'm not sure what can I do to make it work.
Thanks

**Comment by thijstriemstra** [comment]
>  I'm saying that the screen is working right now with a (crappy) old driver.

what driver specifically?

**Comment by Shirkamdev** [comment]
This one: [Adafruit_Python_SSD1306](https://github.com/adafruit/Adafruit_Python_SSD1306)

**Comment by thijstriemstra** [comment]
>  I'm saying that the screen is working right now with a (crappy) old driver. I'm not sure what can I do to make it work.

if it works, it works..?
