### ISSUE TITLE
"Python usage" didn't appear to work, consider amending documentation with sleep statement

### ISSUE THREAD

**Issue by ed-french** [rm-hull/luma.oled#262]
Platform: Raspberry Pi 4
Display: SSD1306 128x64 monochrome oled 1bpp 
Connection: i2c (Channel 1)
Address: 0x3c

(tests repeated with second (different type) display and behaved identically)

Followed install instructions precisely (several times).
Followed instructions in python usage.
Correctly identified display as SSD1306
Nothing displays
No error messages reported

Downloaded "Terminal" example and "Clock" example together with the demo_opts.py
Both run correctly.

**Comment by ed-french** [comment]
I think I found out my problem. When the program ends immediately following the example code the display is blank, however if I add a sleep statement on the end, the message appears as expected.
Please consider adding a message to the documentation on usage and add the sleep statement to the end of the example.

**Comment by rm-hull** [comment]
This behaviour is by design: when the program ends, it runs a cleanup job that puts the OLED display in a low-power state (which effectively turns the screen off) and closes any open devices/channels.

If you don't want this happening either (1) keep the program running, or (2) have a look at issue #140 , and also: rm-hull/luma.core#74

**Comment by ed-french** [comment]
Sorry I wasn't clear enough, I wasn't suggesting any change to the behaviour, but to the documentation. Not knowing this was the behaviour meant I spent a ton of time trying to find out why nothing (appeared) to happen. I've put in a suggested change to the wording.
